/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.carshop.application;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class CarShopApplicationTest {
    @Test void appHasAGreeting() {
        CarShopApplication classUnderTest = new CarShopApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
