/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ecse223.car.shop.application;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
